networks:
  1panel-network:
    external: true
services:
  emby:
    container_name: emby
    devices:
    - /dev/dri:/dev/dri
    environment:
    - UID=0
    - GID=0
    - GIDLIST=0
    - HTTP_PROXY=${HTTP_PROXY:-}
    - HTTPS_PROXY=${HTTP_PROXY:-}
    - NO_PROXY=localhost,127.0.0.1,::1
    image: emby/embyserver:4.9.1.1
    labels:
      createdBy: Apps
    network_mode: ${NETWORK_MODE}
    ports:
    - ${PANEL_APP_PORT_HTTP}:8096
    restart: always
    volumes:
    - /etc/timezone:/etc/timezone
    - /etc/localtime:/etc/localtime
    - ${EMBY_ROOT_PATH}/config:/config
    - ${EMBY_ROOT_PATH}/mnt:/mnt
    - ${CUSTOM_MOUNT_DIRECTORY_1:-./default_mount_1}:${CUSTOM_MOUNT_DIRECTORY_1:-/default_mount_1}
    - ${CUSTOM_MOUNT_DIRECTORY_2:-./default_mount_2}:${CUSTOM_MOUNT_DIRECTORY_2:-/default_mount_2}
    - ${CUSTOM_MOUNT_DIRECTORY_3:-./default_mount_3}:${CUSTOM_MOUNT_DIRECTORY_3:-/default_mount_3}
