networks:
  1panel-network:
    external: true

services:
  chronoframe:
    image: hoshinosuzumi/chronoframe:0.14.1
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:3000
    env_file:
      - ${GLOBAL_ENV_FILE:-/etc/1panel/envs/global.env}
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - ${CHRONOFRAME_ROOT_PATH}/data:/app/data
    environment:
      - TZ=Asia/Shanghai
