networks:
  1panel-network:
    external: true
services:
  excalidraw:
    container_name: excalidraw
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    healthcheck:
      disable: true
      test:
      - CMD
      - curl
      - -f
      - http://localhost
    image: excalidraw/excalidraw:latest
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:80
    restart: always
    stdin_open: true
