networks:
  1panel-network:
    external: true
services:
  artalk:
    container_name: artalk
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    - ATK_DEBUG=false
    - ATK_HOST=0.0.0.0
    - ATK_PORT=23366
    - ATK_IP_REGION_ENABLED=true
    - ATK_DB_TABLE_PREFIX=atk_
    image: artalk/artalk-go:2.9.1
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:23366
    restart: always
    volumes:
    - ${ARTALK_ROOT_PATH}/data:/data
