networks:
  1panel-network:
    external: true
services:
  nacos:
    container_name: nacos
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - MODE=standalone
    - NACOS_CONSOLE_PORT=${PANEL_APP_PORT_HTTP:-8080}
    - NACOS_SERVER_PORT=${PANEL_APP_PORT_API:-8848}
    - NACOS_AUTH_ENABLE=true
    - SPRING_DATASOURCE_PLATFORM=mysql
    image: nacos/nacos-server:v3.0.0
    labels:
      createdBy: Apps
    network_mode: ${NETWORK_MODE}
    ports:
    - ${PANEL_APP_PORT_HTTP:-8080}:${PANEL_APP_PORT_HTTP:-8080}
    - ${PANEL_APP_PORT_API:-8848}:${PANEL_APP_PORT_API:-8080}
    - ${PANEL_APP_PORT_GRPC}:9848
    restart: always
    volumes:
    - ${NACOS_ROOT_PATH}/logs:/home/nacos/logs
    - ${NACOS_ROOT_PATH}/data:/home/nacos/data
