networks:
  1panel-network:
    external: true
services:
  sun-panel:
    container_name: sun-panel
    env_file:
    - ./envs/global.env
    - .env
    image: hslr/sun-panel:1.8.0
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:3002
    restart: always
    volumes:
    - ${SUN_PANEL_ROOT_PATH}/conf:/app/conf
    - ${SUN_PANEL_ROOT_PATH}/database:/app/database
    - ${SUN_PANEL_ROOT_PATH}/uploads:/app/uploads
    - /var/run/docker.sock:/var/run/docker.sock
