networks:
  1panel-network:
    external: true
services:
  element-web:
    container_name: element-web
    env_file:
    - ./envs/global.env
    - .env
    image: vectorim/element-web:v1.11.99
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:80
    restart: always
    volumes:
    - ${ELEMENT_WEB_ROOT_PATH}/config/config.json:/app/config.json
