networks:
  1panel-network:
    external: true
services:
  pihole:
    container_name: pi-hole
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    image: pihole/pihole:2025.02.3
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:80
    - ${PANEL_APP_PORT_DNS}:53
    - ${PANEL_APP_PORT_DNS}:53/udp
    restart: always
    volumes:
    - ${PIHOLE_ROOT_PATH}/pihole:/etc/pihole
    - ${PIHOLE_ROOT_PATH}/dnsmasq.d:/etc/dnsmasq.d
