networks:
  1panel-network:
    external: true
services:
  stream-rec-frontend:
    container_name: stream-rec-frontend
    env_file:
    - ./envs/global.env
    - .env
    image: streamrec/stream-rec-front:v0.7.2
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:15275
    restart: always
