networks:
  1panel-network:
    external: true
services:
  zerotier-planet:
    container_name: zerotier-planet
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - ZT_PORT=${PANEL_APP_PORT_ZT}
    - API_PORT=${PANEL_APP_PORT_HTTP}
    - FILE_SERVER_PORT=${PANEL_APP_PORT_FILE}
    image: xubiaolin/zerotier-planet:1.14.2
    labels:
      createdBy: Apps
    network_mode: ${NETWORK_MODE}
    ports:
    - ${PANEL_APP_PORT_ZT}:${PANEL_APP_PORT_ZT}/tcp
    - ${PANEL_APP_PORT_ZT}:${PANEL_APP_PORT_ZT}/udp
    - ${PANEL_APP_PORT_HTTP}:${PANEL_APP_PORT_HTTP}
    - ${PANEL_APP_PORT_FILE}:${PANEL_APP_PORT_FILE}
    restart: always
    volumes:
    - ${ZEROTIER_PLANET_ROOT_PATH}/file:/app/dist
    - ${ZEROTIER_PLANET_ROOT_PATH}/ztncui:/app/ztncui
    - ${ZEROTIER_PLANET_ROOT_PATH}/zerotier-one:/var/lib/zerotier-one
    - ${ZEROTIER_PLANET_ROOT_PATH}/config:/app/config
