networks:
  1panel-network:
    external: true
services:
  overseerr:
    container_name: overseerr
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - PORT=5055
    - TZ=Asia/Shanghai
    - LOG_LEVEL=debug
    image: sctx/overseerr:c2d4c61fae2053157052f96e5de1cdb490ea704e
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:5055
    restart: always
    volumes:
    - ${OVERSEERR_ROOT_PATH}/config:/app/config
