networks:
  1panel-network:
    external: true

services:
  moontv:
    image: ghcr.io/senshinya/moontv:latest
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:3000
    env_file:
      - ${GLOBAL_ENV_FILE:-/etc/1panel/envs/global.env}
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - ${MOONTV_ROOT_PATH}/data:/data
    environment:
      - TZ=Asia/Shanghai
