networks:
  1panel-network:
    external: true
services:
  beszel:
    container_name: beszel
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    image: henrygd/beszel:0.11.0
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:8090
    restart: always
    volumes:
    - ${BESZEL_ROOT_PATH}/data:/beszel_data
