networks:
  1panel-network:
    external: true
services:
  uptime-kuma:
    container_name: uptime-kuma
    env_file:
    - ./envs/global.env
    - .env
    image: louislam/uptime-kuma:2.0.2
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:3001
    restart: always
    volumes:
    - ${UPTIME_KUMA_ROOT_PATH}/data:/app/data
    - /var/run/docker.sock:/var/run/docker.sock
