networks:
  1panel-network:
    external: true
services:
  bark:
    container_name: yarr
    image: qyg2297248353/yarr:v2.4.0
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:7070
    restart: always
    volumes:
    - ${YARR_ROOT_PATH}/data:/data
