networks:
  1panel-network:
    external: true
services:
  libretv:
    container_name: libretv
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    image: bestzwei/libretv:202507110114
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:8080
    restart: always
