networks:
  1panel-network:
    external: true
services:
  baota:
    container_name: homarr
    env_file:
    - ./envs/global.env
    - .env
    image: ghcr.io/ajnart/homarr:0.15.8
    labels:
      createdBy: Apps
    network_mode: ${NETWORK_MODE}
    ports:
    - ${PANEL_APP_PORT_HTTP}:7575
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ${HOMARR_ROOT_PATH}/configs:/app/data/configs
    - ${HOMARR_ROOT_PATH}/icons:/app/public/icons
    - ${HOMARR_ROOT_PATH}/data:/data
