networks:
  1panel-network:
    external: true
services:
  prowlarr:
    container_name: prowlarr
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - PUID=1000
    - PGID=1000
    - UMASK=022
    - TZ=Asia/Shanghai
    image: linuxserver/prowlarr:1.33.3
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:9696
    restart: always
    volumes:
    - ${PROWLARR_ROOT_PATH}/config:/config
