networks:
  1panel-network:
    external: true
services:
  qinglong:
    container_name: qinglong
    environment:
    - QlPort=5700
    - QlBaseUrl=${QINGLONG_BASE_URL:-/}
    image: whyour/qinglong:2.18.3
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP:-5700}:5700
    restart: always
    volumes:
    - ${QINGLONG_ROOT_PATH}/data:/ql/data
