networks:
  1panel-network:
    external: true
services:
  nezha-dashboard:
    container_name: nezha
    image: ghcr.io/naiba/nezha-dashboard:v0.20.13
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:80
    - ${PANEL_APP_PORT_GRPC}:${PANEL_APP_PORT_GRPC}
    restart: always
    volumes:
    - ${NEZHA_ROOT_PATH}/data:/dashboard/data
    - ${NEZHA_ROOT_PATH}/static-custom/static:/dashboard/resource/static/custom
    - ${NEZHA_ROOT_PATH}/theme-custom/template:/dashboard/resource/template/theme-custom
    - ${NEZHA_ROOT_PATH}/dashboard-custom/template:/dashboard/resource/template/dashboard-custom
