networks:
  1panel-network:
    external: true
services:
  uptime-kuma:
    container_name: uptime-kuma
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - PUID=0
    - PGID=0
    - UPTIME_KUMA_PORT=3001
    - UPTIME_KUMA_HOST=0.0.0.0
    - DATA_DIR=/app/data
    - NODE_TLS_REJECT_UNAUTHORIZED=0
    - UPTIME_KUMA_ALLOW_ALL_CHROME_EXEC=0
    - UPTIME_KUMA_WS_ORIGIN_CHECK=cors-like
    image: louislam/uptime-kuma:1.23.16
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:3001
    restart: always
    volumes:
    - ${UPTIME_KUMA_ROOT_PATH}/data:/app/data
    - /var/run/docker.sock:/var/run/docker.sock
