networks:
  1panel-network:
    external: true
services:
  transmission:
    container_name: transmission
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - PUID=1000
    - PGID=1000
    - PEERPORT= ${PANEL_APP_PORT_TORRENTING}
    - TZ=Asia/Shanghai
    image: linuxserver/transmission:4.0.6
    labels:
      createdBy: Apps
    network_mode: ${NETWORK_MODE}
    ports:
    - ${PANEL_APP_PORT_HTTP}:9091
    - ${PANEL_APP_PORT_TORRENTING}
    - ${PANEL_APP_PORT_TORRENTING}/udp
    restart: always
    volumes:
    - ${TRANSMISSION_ROOT_PATH}/ui/themes:/ui/themes
    - ${TRANSMISSION_ROOT_PATH}/config:/config
    - ${TRANSMISSION_ROOT_PATH}/downloads:/downloads
    - ${TRANSMISSION_ROOT_PATH}/watch:/watch
    - ${CUSTOM_MOUNT_DIRECTORY_1:-./default_mount_1}:${CUSTOM_MOUNT_DIRECTORY_1:-/default_mount_1}
    - ${CUSTOM_MOUNT_DIRECTORY_2:-./default_mount_2}:${CUSTOM_MOUNT_DIRECTORY_2:-/default_mount_2}
    - ${CUSTOM_MOUNT_DIRECTORY_3:-./default_mount_3}:${CUSTOM_MOUNT_DIRECTORY_3:-/default_mount_3}
