name: 💡 提交应用
description: 提交您想要添加到 1Panel 的应用
title: "[应用提交]"
labels: app
assignees: QYG2297248353
body:
  - type: markdown
    id: base_info
    attributes:
      value: "## 基本信息"
  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: "1Panel 版本号"
      description: "请提供您的 1Panel 版本号"
  - type: input
    id: email
    validations:
      required: true
    attributes:
      label: "邮箱"
      description: "请提供您的邮箱"
  - type: dropdown
    id: app_type
    validations:
      required: true
    attributes:
      label: "应用类型"
      multiple: false
      options:
        - 开源
        - 闭源
        - 半开源
      default: 0
  - type: input
    id: app_url
    validations:
      required: true
    attributes:
      label: "应用链接"
      description: "请提供应用的 Docker Hub 或 GitHub 或 官网 链接"
  - type: input
    id: app_name
    attributes:
      label: "应用名称"
      description: "请提供应用的名称"
  - type: input
    id: app_version
    attributes:
      label: "应用版本"
      description: "请提供应用的版本"
  - type: textarea
    id: details
    attributes:
      label: "应用描述"
      description: "请提供应用的描述"
      placeholder: "简单描述需要上架的理由"
  - type: checkboxes
    id: authorization
    attributes:
      label: 条款确认
      description: "请确认您已阅读并同意以下条款"
      options:
        - label: "我已确认该应用 允许在 中国大陆 使用"
          required: true
        - label: "我已确认该应用 符合 中国大陆 相关法律法规"
          required: true
