networks:
  1panel-network:
    external: true

services:
  baihu-panel:
    image: ghcr.io/engigu/baihu:1.1.23
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:8052
    env_file:
      - ${GLOBAL_ENV_FILE:-/etc/1panel/envs/global.env}
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - ${BAIHU_ROOT_PATH}/data:/app/data
      - ${BAIHU_ROOT_PATH}/envs:/app/envs
    environment:
      - TZ=Asia/Shanghai
      - BH_SERVER_PORT=8052
      - BH_SERVER_HOST=0.0.0.0
      - BH_DB_TYPE=sqlite
      - BH_DB_PATH=/app/data/baihu.db
      - BH_DB_TABLE_PREFIX=baihu_
      - BH_DB_NAME=baihu
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
