networks:
  1panel-network:
    external: true
services:
  stream-rec-backend:
    container_name: stream-rec-backend
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - LOG_LEVEL=INFO
    - DB_PATH=/opt/records
    - DOWNLOAD_PATH=/download
    image: streamrec/stream-rec:main
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:12555
    restart: always
    volumes:
    - ${STREAM_REC_ROOT_PATH}/records:/opt/records
    - ${STREAM_REC_ROOT_PATH}/download:/download
