networks:
  1panel-network:
    external: true
services:
  garage:
    container_name: garage-hq-web
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    image: dxflrs/garage:v2.1.0
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_S3_API}:3900
    - ${PANEL_APP_PORT_RPC}:3901
    - ${PANEL_APP_PORT_S3_WEB}:3902
    - ${PANEL_APP_PORT_API}:3903
    restart: always
    volumes:
    - ${GARAGE_ROOT_PATH}/config/garage.toml:/etc/garage.toml
    - ${GARAGE_ROOT_PATH}/meta:/var/lib/garage/meta
    - ${GARAGE_ROOT_PATH}/data:/var/lib/garage/data
  garage-webui:
    container_name: garage-hq-web-web
    environment:
      API_BASE_URL: http://garage:3903
      S3_ENDPOINT_URL: http://garage:3900
    image: khairul169/garage-webui:1.1.0
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:3909
    restart: always
    volumes:
    - ${GARAGE_ROOT_PATH}/config/garage.toml:/etc/garage.toml
