networks:
  1panel-network:
    external: true
services:
  iycms:
    container_name: iycms
    env_file:
    - ./envs/global.env
    - .env
    image: qyg2297248353/iycms:v3.3.44
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:80
    - ${PANEL_APP_PORT_ADMIN}:21007
    restart: always
    volumes:
    - ${IYCMS_ROOT_PATH}/iycms:/app/iycms
