networks:
  1panel-network:
    external: true
services:
  vertex:
    container_name: vertex
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    - PORT=3000
    image: lswl/vertex:stable
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:3000
    restart: always
    volumes:
    - ${VERTEX_ROOT_PATH}/data:/vertex
