networks:
  1panel-network:
    external: true
services:
  nezha:
    container_name: nezha
    environment:
    - NZ_LISTEN_PORT=${PANEL_APP_PORT_HTTP}
    - NZ_LOCATION=Asia/Shanghai
    image: ghcr.io/nezhahq/nezha:v1.14.8
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:${PANEL_APP_PORT_HTTP}
    restart: always
    volumes:
    - ${NEZHA_ROOT_PATH}/data:/dashboard/data
