networks:
  1panel-network:
    external: true
services:
  nexusphp:
    container_name: nexusphp
    env_file:
    - ./envs/global.env
    - .env
    image: qyg2297248353/nexusphp:v1.8.16
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:80
    restart: always
    volumes:
    - ${NEXUSPHP_ROOT_PATH}/config/.env.example:/var/www/html/.env.example
    - ${NEXUSPHP_ROOT_PATH}/data:/var/www/html
    - ${NEXUSPHP_TORRENTS_ROOT_PATH}/torrents:/var/www/html/torrents
    - ${NEXUSPHP_BITBUCKET_ROOT_PATH}/bitbucket:/var/www/html/bitbucket
    - ${NEXUSPHP_ATTACHMENTS_ROOT_PATH}/attachments:/var/www/html/attachments
