networks:
  1panel-network:
    external: true
services:
  dujiaoka:
    container_name: dujiaoka
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - WEB_DOCUMENT_ROOT=/app/public
    - DUJIAO_ADMIN_LANGUAGE=zh_CN
    - BROADCAST_DRIVER=log
    - SESSION_DRIVER=file
    - SESSION_LIFETIME=120
    - LOG_CHANNEL=stack
    - APP_DEBUG=false
    - APP_ENV=local
    - DB_CONNECTION=mysql
    image: qyg2297248353/dujiaoka:v2.1.0
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:80
    - ${PANEL_APP_PORT_API}:9000
    restart: always
    tty: true
    volumes:
    - ${DUJIAOKA_ROOT_PATH}/app:/app
