networks:
  1panel-network:
    external: true
services:
  n8n:
    container_name: n8n
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    - N8N_LISTEN_ADDRESS=0.0.0.0
    - N8N_PORT=5678
    - N8N_PROTOCOL=http
    - N8N_DIAGNOSTICS_ENABLED=false
    - N8N_SECURE_COOKIE=false
    image: n8nio/n8n:1.106.0
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:5678
    restart: always
    volumes:
    - ${N8N_ROOT_PATH}/data:/home/node/.n8n
