networks:
  1panel-network:
    external: true
services:
  baihu-panel:
    container_name: baihu-panel
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    - BH_SERVER_PORT=8052
    - BH_SERVER_HOST=0.0.0.0
    - BH_DB_TYPE=sqlite
    - BH_DB_PATH=/app/data/baihu.db
    - BH_DB_TABLE_PREFIX=baihu_
    - BH_DB_NAME=baihu
    image: ghcr.io/engigu/baihu:1.0.44
    labels:
      createdBy: Apps
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 10m
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:8052
    restart: always
    volumes:
    - ${BAIHU_ROOT_PATH}/data:/app/data
    - ${BAIHU_ROOT_PATH}/envs:/app/envs
