networks:
  1panel-network:
    external: true
services:
  teemii-backend:
    container_name: backend-teemii
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - EXPRESS_PORT=3000
    - SOCKET_IO_PORT=1555
    image: dokkaner/teemii-backend:0.8.2
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    restart: always
    volumes:
    - ${TEEMII_ROOT_PATH}/data:/data
  teemii-frontend:
    container_name: frontend-teemii
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - VITE_APP_PORT=80
    image: dokkaner/teemii-frontend:0.8.2
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:80
    restart: always
