networks:
  1panel-network:
    external: true
services:
  paopao-ce:
    container_name: paopao-ce-all
    env_file:
    - ./envs/global.env
    - .env
    image: bitbus/paopao-ce:all-in-one-0.6-alpha
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:8008
    - ${PANEL_APP_PORT_MEILI}:7700
    restart: always
    volumes:
    - ${PAOPAO_CE_ROOT_PATH}/config/config.yaml:/app/config.yaml
    - ${PAOPAO_CE_ROOT_PATH}/custom:/app/custom
    - ${PAOPAO_CE_ROOT_PATH}/meili_data:/app/meili_data
