networks:
  1panel-network:
    external: true
services:
  percona:
    command:
    - --default-authentication-plugin=mysql_native_password
    container_name: percona
    env_file:
    - ./envs/global.env
    - .env
    image: percona:8.0
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:3306
    restart: always
    user: ${UID:-1000}:${GID:-1000}
    volumes:
    - ${PERCONA_ROOT_PATH}/data:/var/lib/mysql
    - ${PERCONA_ROOT_PATH}/config/my.cnf:/etc/my.cnf
    - ${PERCONA_ROOT_PATH}/log:/var/log/mysql
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
