networks:
  1panel-network:
    external: true
services:
  metatube-server:
    container_name: metatube-server-memory
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - HTTPS_PROXY=${HTTP_PROXY}
    - DB_AUTO_MIGRATE=true
    - PORT=${PANEL_APP_PORT_HTTP}
    image: ghcr.io/metatube-community/metatube-server:1.3.2
    labels:
      createdBy: Apps
    network_mode: ${NETWORK_MODE}
    ports:
    - ${PANEL_APP_PORT_HTTP}:${PANEL_APP_PORT_HTTP}
    restart: always
