networks:
  1panel-network:
    external: true
services:
  peerbanhelper:
    container_name: peer-ban-helper
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - PUID=0
    - PGID=0
    - TZ=Asia/Shanghai
    image: ghostchu/peerbanhelper:v8.0.9
    labels:
      createdBy: Apps
    network_mode: ${NETWORK_MODE:-host}
    ports:
    - ${PANEL_APP_PORT_HTTP}:9898
    restart: always
    volumes:
    - ${PEERBANHELPER_ROOT_PATH}/app:/app/data
