networks:
  1panel-network:
    external: true
services:
  bonita:
    container_name: bonita
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - PUID=0
    - PGID=0
    - TZ=Asia/Shanghai
    image: suwmlee/bonita:0.10.1
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:12346
    restart: always
    volumes:
    - ${BONITA_ROOT_PATH}/data:/app/backend/data
    - ${BONITA_ROOT_PATH}/media:/media
