networks:
  1panel-network:
    external: true
  dujiao-net:
    driver: bridge
services:
  dujiaonext-admin:
    container_name: admin-dujiaonext
    depends_on:
      dujiaonext-api:
        condition: service_healthy
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    image: dujiaonext/admin:v0.1.1
    networks:
    - dujiao-net
    ports:
    - ${PANEL_APP_PORT_ADMIN}:80
    restart: always
  dujiaonext-api:
    container_name: dujiaonext
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    - QUEUE_HOST=${REDIS_HOST:-}
    - QUEUE_PORT=${REDIS_PORT:-}
    - QUEUE_PASSWORD=${REDIS_PASSWORD:-}
    - QUEUE_DB=${REDIS_DB:-}
    healthcheck:
      interval: 10s
      retries: 10
      test:
      - CMD
      - wget
      - -qO-
      - http://127.0.0.1:8080/health
      timeout: 3s
    image: dujiaonext/api:v0.1.1
    labels:
      createdBy: Apps
    networks:
    - dujiao-net
    ports:
    - ${PANEL_APP_PORT_API}:8080
    restart: always
    volumes:
    - ${DUJIAONEXT_ROOT_PATH}/config/config.yml:/app/config.yml:ro
    - ${DUJIAONEXT_ROOT_PATH}/data/db:/app/db
    - ${DUJIAONEXT_ROOT_PATH}/data/uploads:/app/uploads
    - ${DUJIAONEXT_ROOT_PATH}/data/logs:/app/logs
  dujiaonext-user:
    container_name: user-dujiaonext
    depends_on:
      dujiaonext-api:
        condition: service_healthy
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    image: dujiaonext/user:v0.1.1
    networks:
    - dujiao-net
    ports:
    - ${PANEL_APP_PORT_HTTP}:80
    restart: always
