networks:
  1panel-network:
    external: true
services:
  puff:
    container_name: puff
    env_file:
    - ./envs/global.env
    - .env
    image: bitaur/puff:v0.2.2
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:8080
    restart: always
    volumes:
    - ${PUFF_ROOT_PATH}/data:/app/data
