networks:
  1panel-network:
    external: true

services:
  shopware:
    image: ghcr.io/shopwarelabs/devcontainer/base-slim:8.3
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:8000
      - ${PANEL_APP_PORT_WEB}:5173
      - ${PANEL_APP_PORT_WS}:9998
      - ${PANEL_APP_PORT_API}:9999
    env_file:
      - ${GLOBAL_ENV_FILE:-/etc/1panel/envs/global.env}
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - ${SHOPWARE_ROOT_PATH}/html:/var/www/html
    environment:
      - TZ=Asia/Shanghai
      - COMPOSER_ROOT_VERSION=6.7.9999999-dev
      - HOST='0.0.0.0'
      - APP_URL=http://localhost:8000
      - DATABASE_URL=mysql://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}
      - MAILER_DSN=smtp://mailer:1025
      - OPENSEARCH_URL=http://opensearch:9200
      - ADMIN_OPENSEARCH_URL=http://opensearch:9200

  shopware-mailer:
    image: axllent/mailpit
    container_name: mailer-${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_MAILER}:8025

  shopware-opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    environment:
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: 'c3o_ZPHo!'
      discovery.type: single-node
      plugins.security.disabled: 'true'

  valkey:
    image: valkey/valkey:alpine
    command: [ "--maxmemory-policy", "volatile-lfu", "--save", "", "--appendonly", "no" ]
