networks:
  1panel-network:
    external: true
services:
  cloudreve:
    container_name: cloudreve
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    image: cloudreve/cloudreve:4.9.1
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:5212
    restart: always
    volumes:
    - ${CLOUDREVE_ROOT_PATH}/data:/cloudreve/data
