networks:
  1panel-network:
    external: true
services:
  baota:
    container_name: baota
    env_file:
    - ./envs/global.env
    - .env
    expose:
    - 888
    - 22
    - 21
    - 3306
    - 80
    - 443
    image: btpanel/baota:10.0_lts
    labels:
      createdBy: Apps
    network_mode: ${NETWORK_MODE}
    ports:
    - ${PANEL_APP_PORT_HTTP}:8888
    restart: always
    volumes:
    - ${BAOTA_ROOT_PATH}/wwwroot:/www/wwwroot
    - ${BAOTA_ROOT_PATH}/data:/www/server/data
    - ${BAOTA_ROOT_PATH}/vhost:/www/server/panel/vhost
