networks:
  1panel-network:
    external: true

services:
  splayer:
    image: imsyy/splayer:latest
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:25884
    env_file:
      - ${GLOBAL_ENV_FILE:-/etc/1panel/envs/global.env}
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    environment:
      - TZ=Asia/Shanghai
      - ENABLE_HTTPDNS=false
      - BLOCK_ADS=true
      - DISABLE_UPGRADE_CHECK=false
      - DEVELOPMENT=false
      - FOLLOW_SOURCE_ORDER=true
      - JSON_LOG=false
      - NO_CACHE=false
      - SELECT_MAX_BR=true
      - LOG_LEVEL=info
      - SEARCH_ALBUM=true
