networks:
  1panel-network:
    external: true
services:
  wukongim:
    container_name: wukongim
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - WK_MODE=release
    image: wukongim/wukongim:v1.2.6
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:5300
    - ${PANEL_APP_PORT_WK_API}:5001
    - ${PANEL_APP_PORT_WK_TCP}:5100
    - ${PANEL_APP_PORT_WK_WS}:5200
    - ${PANEL_APP_PORT_WK_DEMO_SERVER}:5172
    restart: always
    volumes:
    - ${WUKONGIM_ROOT_PATH}/wukongim:/root/wukongim
