networks:
  1panel-network:
    external: true
services:
  reader3-webview:
    container_name: reader3-webview
    env_file:
    - ./envs/global.env
    image: hectorqin/remote-webview:3.2.0
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:8050
    restart: always
