networks:
  1panel-network:
    external: true
services:
  cloudsaver:
    container_name: cloudsaver
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 5s
      test: 'CMD-SHELL node -e "require(''http'').get(''http://localhost:8008/health'',
        res => (res.statusCode >= 200 && res.statusCode < 400) ? process.exit(0) :
        process.exit(1)).on(''error'', () => process.exit(1))"

        '
      timeout: 3s
    image: jiangrui1994/cloudsaver:v0.6.0
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:8008
    restart: always
    volumes:
    - ${CLOUDSAVER_ROOT_PATH}/data:/app/data
    - ${CLOUDSAVER_ROOT_PATH}/config:/app/config
