networks:
  1panel-network:
    external: true
services:
  mx-server:
    container_name: mx-space
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    - PORT=2333
    - DEMO=false
    - NODE_ENV=production
    - ENCRYPT_ENABLE=false
    image: innei/mx-server:8.4.0
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:2333
    restart: always
    volumes:
    - ${MX_SERVER_ROOT_PATH}/data:/root/.mx-space
