networks:
  1panel-network:
    external: true
services:
  cookie-cloud:
    container_name: cookie-cloud
    env_file:
    - ./envs/global.env
    - .env
    image: easychen/cookiecloud:latest
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:8088
    restart: always
    volumes:
    - ${COOKIECLOUD_ROOT_PATH}/data:/data/api/data
