networks:
  1panel-network:
    external: true
services:
  speedtest:
    container_name: speedtest
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - MODE=standalone
    - WEBPORT=80
    image: ghcr.io/librespeed/speedtest:5.4.1
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:80
    restart: always
    volumes:
    - ${SPEED_TEST_ROOT_PATH}/database:/database
