networks:
  1panel-network:
    external: true
services:
  dpanel:
    container_name: dpanel
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - APP_NAME=${CONTAINER_NAME}
    image: dpanel/dpanel:1.3.1
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_ADMIN}:8080
    - ${PANEL_APP_PORT_HTTP}:80
    - ${PANEL_APP_PORT_HTTPS}:443
    restart: always
    volumes:
    - ${DPANEL_ROOT_PATH}/data:/dpanel
    - ${DPANEL_ROOT_PATH}/compose:/dpanel/compose
    - /var/run/docker.sock:/var/run/docker.sock
  dpanel-plugin-explorer:
    command:
    - sh
    - -c
    - tail -f /dev/null
    container_name: dpanel-plugin-explorer
    image: alpine:latest
    pid: host
    privileged: true
    restart: unless-stopped
