networks:
  1panel-network:
    external: true
services:
  halo:
    command:
    - --spring.r2dbc.url=r2dbc:pool:${DB_TYPE}://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}
    - --spring.r2dbc.username=${DB_USER}
    - --spring.r2dbc.password=${DB_USER_PASSWORD}
    - --spring.sql.init.platform=${DB_TYPE}
    - --halo.external-url=${HALO_EXTERNAL_URL}
    - --halo.security.remember-me.token-validity=${HALO_REMEMBER_ME_TOKEN_VALIDITY}
    container_name: halo
    image: halohub/halo:2.20.18
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:8090
    restart: always
    volumes:
    - ${HALO_ROOT_PATH}/data:/root/.halo2
