networks:
  1panel-network:
    external: true
services:
  pingvin-share:
    container_name: pingvin-share
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - BACKEND_PORT=8080
    - PORT=3333
    - API_URL=http://localhost:8080
    - TRUST_PROXY=false
    image: stonith404/pingvin-share:v1.12.0
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:3333
    restart: always
    volumes:
    - ${PINGVIN_SHARE_ROOT_PATH}/data:/opt/app/backend/data
    - ${PINGVIN_SHARE_ROOT_PATH}/images:/opt/app/frontend/public/img
