name: immich
networks:
  1panel-network:
    external: true
services:
  immich-pg14-vectors:
    container_name: pg14-vectors-immich-no-machine
    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME:-immich}
      POSTGRES_INITDB_ARGS: --data-checksums
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_DB:-5432}:5432
    restart: always
    volumes:
    - ${IMMICH_ROOT_PATH}/pg14/data:/var/lib/postgresql/data
  immich-server:
    container_name: immich-no-machine
    depends_on:
    - immich-pg14-vectors
    devices:
    - /dev/dri:/dev/dri
    env_file:
    - ./envs/global.env
    - .env
    image: ghcr.io/immich-app/immich-server:v2.0.1
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:2283
    restart: always
    volumes:
    - ${IMMICH_ROOT_PATH}/data/library:/data
    - /etc/localtime:/etc/localtime
