networks:
  1panel-network:
    external: true

services:
  termix:
    image: ghcr.io/lukegus/termix:latest
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:8080
    env_file:
      - ${GLOBAL_ENV_FILE:-/etc/1panel/envs/global.env}
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - ${TERMIX_ROOT_PATH}/data:/app/data
    environment:
      - TZ=Asia/Shanghai
      - PORT=8080
