networks:
  1panel-network:
    external: true
services:
  telegram-bot-api:
    container_name: telegram-bot-api
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TELEGRAM_STAT=1
    - TELEGRAM_LOCAL=1
    - TELEGRAM_VERBOSITY=1
    - TELEGRAM_MAX_WEBHOOK_CONNECTIONS=100000
    - TELEGRAM_LOG_FILE=/var/log/telegram-bot-api/telegram-bot-api.log
    - TELEGRAM_MAX_CONNECTIONS=1024
    image: aiogram/telegram-bot-api:9.1
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTPS}:8081
    - ${PANEL_APP_PORT_HTTP}:8082
    restart: always
    volumes:
    - ${TELEGRAM_BOT_API_ROOT_PATH}/data:/var/lib/telegram-bot-api
    - ${TELEGRAM_BOT_API_ROOT_PATH}/logs:/var/log/telegram-bot-api
