networks:
  1panel-network:
    external: true
services:
  movie-pilot-v2:
    container_name: movie-pilot
    env_file:
    - ./envs/global.env
    - ./envs/movie-pilot.env
    - .env
    environment:
    - NGINX_PORT=3000
    - PORT=3001
    - PUID=0
    - PGID=0
    - UMASK=022
    - HTTP_PROXY=${PROXY_HOST}
    - HTTPS_PROXY=${PROXY_HOST}
    image: jxxghp/moviepilot-v2:2.1.2
    labels:
      createdBy: Apps
    logging:
      driver: json-file
      options:
        max-size: 5m
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:3000
    - ${PANEL_APP_PORT_API}:3001
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ${MOVIEPILOT_ROOT_PATH}/config:/config
    - ${MOVIEPILOT_ROOT_PATH}/moviepilot:/moviepilot
    - ${MOVIEPILOT_ROOT_PATH}/download:/download
    - ${CUSTOM_MOUNT_DIRECTORY_1:-./default_mount_1}:${CUSTOM_MOUNT_DIRECTORY_1:-/default_mount_1}
    - ${CUSTOM_MOUNT_DIRECTORY_2:-./default_mount_2}:${CUSTOM_MOUNT_DIRECTORY_2:-/default_mount_2}
    - ${CUSTOM_MOUNT_DIRECTORY_3:-./default_mount_3}:${CUSTOM_MOUNT_DIRECTORY_3:-/default_mount_3}
