networks:
  1panel-network:
    external: true
services:
  windows:
    cap_add:
    - NET_ADMIN
    container_name: macos
    devices:
    - /dev/kvm:/dev/kvm
    - /dev/dri:/dev/dri
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - VERSION=${VERSION}
    image: dockurr/macos:2.06
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:8006
    - ${PANEL_APP_PORT_REMOTE}:5900/tcp
    - ${PANEL_APP_PORT_REMOTE}:5900/udp
    restart: always
    stop_grace_period: 2m
    volumes:
    - ${MACOS_STORAGE_ROOT_PATH}/storage:/storage
