database:
  # Database type: postgres, pglite
  type: postgres
  host: telegram_search_pgvector
  port: 5432
  user: postgres
  password: 'telegram_search'
  database: postgres

api:
  telegram:
    apiId: '611335'
    apiHash: d524b414d21f4d37f08684c1df41ac9c
    receiveMessage: false
    proxy:
      ip: ''
      port: 0
      MTProxy: false
      secret: ''
      socksType: 5
      timeout: 2
      username: ''
      password: ''
  embedding:
    # Embedding provider (openai or ollama)
    provider: openai
    # Embedding model
    model: text-embedding-3-small
    # API key for provider
    apiKey: your_openai_api_key
    # Optional, available dimensions: 1536, 1024, 768. Default dimension is 1536. #If using gemini-embedding-exp-03-07, choose 768
    dimension: 1536
    # Optional, for custom API providers
    apiBase: 'https://api.openai.com/v1'
