networks:
  1panel-network:
    external: true

services:
  baota:
    image: btpanel/baota:9.0_lts_latest
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    network_mode: ${NETWORK_MODE}
    ports:
      - ${PANEL_APP_PORT_HTTP}:8888
    expose:
      - 888
      - 22
      - 21
      - 3306
      - 80
      - 443
    env_file:
      - ${GLOBAL_ENV_FILE:-/etc/1panel/envs/global.env}
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - ${BAOTA_ROOT_PATH}/wwwroot:/www/wwwroot
      - ${BAOTA_ROOT_PATH}/data:/www/server/data
      - ${BAOTA_ROOT_PATH}/vhost:/www/server/panel/vhost
