networks:
  1panel-network:
    external: true
services:
  maccms10:
    container_name: maccms10
    env_file:
    - ./envs/global.env
    - .env
    image: qyg2297248353/maccms10:v24.11.19
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:80
    restart: always
    volumes:
    - ${MACCMS10_ROOT_PATH}/iycms:/app/iycms
