networks:
  1panel-network:
    external: true
services:
  aria2-superng6:
    cap_add:
    - NET_ADMIN
    container_name: aria2-superng6
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - PUID=0
    - PGID=0
    - UMASK=022
    - WEBUI=true
    - WEBUI_PORT=${PANEL_APP_PORT_HTTP}
    - BTPORT=${PANEL_APP_PORT_BTPORT}
    - PORT=${PANEL_APP_PORT_RPC}
    - UT=true
    - RUT=true
    - SMD=true
    - CRA2B=2h
    - QUIET=true
    image: superng6/aria2:a2b-stable-24-11-01
    labels:
      createdBy: Apps
    network_mode: ${NETWORK_MODE}
    ports:
    - ${PANEL_APP_PORT_HTTP}:8080
    - ${PANEL_APP_PORT_RPC}:6800
    - ${PANEL_APP_PORT_BTPORT}:32516
    - ${PANEL_APP_PORT_BTPORT}:32516/udp
    restart: always
    volumes:
    - ${ARIA2_ROOT_PATH}/downloads:/downloads
    - ${ARIA2_ROOT_PATH}/config:/config
    - /lib/modules:/lib/modules
