networks:
  1panel-network:
    external: true
services:
  linkding:
    container_name: linkding
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - LD_SERVER_PORT=9090
    - LD_DB_ENGINE=postgres
    - HTTP_PROXY=${ALL_PROXY}
    - HTTPS_PROXY=${ALL_PROXY}
    image: sissbruecker/linkding:1.41.0-plus
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:9090
    restart: always
    ulimits:
      nofile:
        hard: 40000
        soft: 20000
      nproc: 65535
    volumes:
    - ${LINKDING_ROOT_PATH}/data:/etc/linkding/data
