networks:
  1panel-network:
    external: true
services:
  moontv:
    container_name: moontv
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    image: ghcr.io/senshinya/moontv:latest
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:3000
    restart: always
    volumes:
    - ${MOONTV_ROOT_PATH}/data:/data
