networks:
  1panel-network:
    external: true
services:
  nodebb:
    container_name: nodebb
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    - NODEBB_PORT=4567
    - NODEBB_URL=http://127.0.0.1:4567
    image: ghcr.io/nodebb/nodebb:3.12.2
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:4567
    restart: always
    volumes:
    - ${NODEBB_ROOT_PATH}/build:/usr/src/app/build
    - ${NODEBB_ROOT_PATH}/uploads:/usr/src/app/public/uploads
    - ${NODEBB_ROOT_PATH}/config:/opt/config
