networks:
  1panel-network:
    external: true
services:
  watchyourlan:
    container_name: watchyourlan
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - HOST=0.0.0.0
    - PORT=8840
    - LOG_LEVEL=info
    image: aceberg/watchyourlan:2.1.2
    labels:
      createdBy: Apps
    network_mode: host
    ports:
    - ${PANEL_APP_PORT_HTTP}:8840
    restart: always
    volumes:
    - ${WATCHYOURLAN_ROOT_PATH}/data:/data/WatchYourLAN
