networks:
  1panel-network:
    external: true
services:
  mysql:
    command:
    - --character-set-server=utf8mb4
    - --lower_case_table_names=1
    - --collation-server=utf8mb4_general_ci
    - --explicit_defaults_for_timestamp=true
    container_name: mysql
    env_file:
    - ./envs/global.env
    - .env
    image: mysql:5.7.44
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:3306
    restart: always
    user: 1000:1000
    volumes:
    - ${MYSQL_ROOT_PATH}/data/:/var/lib/mysql
    - ${MYSQL_ROOT_PATH}/config/my.cnf:/etc/mysql/my.cnf
    - ${MYSQL_ROOT_PATH}/log:/var/log/mysql
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
