networks:
  1panel-network:
    external: true

services:
  nezha:
    image: ghcr.io/nezhahq/nezha:v1.14.9
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:${PANEL_APP_PORT_HTTP}
    volumes:
      - ${NEZHA_ROOT_PATH}/data:/dashboard/data
    environment:
      - NZ_LISTEN_PORT=${PANEL_APP_PORT_HTTP}
      - NZ_LOCATION=Asia/Shanghai
