networks:
  1panel-network:
    external: true
services:
  mariadb:
    container_name: mariadb
    env_file:
    - ./envs/global.env
    - .env
    image: mariadb:11.8.3
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:3306
    restart: always
    volumes:
    - ${MARIADB_ROOT_PATH}/data:/var/lib/mysql
    - ${MARIADB_ROOT_PATH}/config/my.cnf:/etc/mysql/my.cnf
