networks:
  1panel-network:
    external: true
services:
  bookstack:
    container_name: bookstack
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    - PUID=1000
    - PGID=1000
    - QUEUE_CONNECTION=database
    image: linuxserver/bookstack:25.05.2
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:80
    restart: always
    volumes:
    - ${BOOKSTACK_ROOT_PATH}/config:/config
