networks:
  1panel-network:
    external: true
services:
  kvrocks:
    container_name: kvrocks
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    image: apache/kvrocks:2.13.0
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:6666
    restart: always
    volumes:
    - ${KVROCKS_ROOT_PATH}/data:/kvrocks_data
