name: Auto Process Renovate PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '0 * * * *' # 每小时运行一次，处理可能错过的PR

jobs:
  process-renovate-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Process Renovate PRs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat << 'EOF' > process_renovate_prs.py
          # 在这里插入下面的Python脚本内容
          EOF
          python process_renovate_prs.py

      - name: Clean up
        run: rm -f process_renovate_prs.py
