name: Renovate Automerge

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup GitHub CLI
        uses: cli/cli-action@v2
        with:
          version: latest

      - name: Find Renovate PRs
        id: find_prs
        run: |
          prs=$(gh pr list \
            --repo ${{ github.repository }} \
            --state open \
            --json number,title,author \
            --jq '.[] | select(.author.login | test("renovate"; "i")) | .number')

          echo "Found PRs: $prs"
          echo "prs=$prs" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Process PRs
        if: env.prs != ''
        run: |
          for pr in $prs; do
            echo "Checking PR #$pr ..."
            body=$(gh pr view "$pr" \
              --repo ${{ github.repository }} \
              --json body \
              --jq .body)

            # 提取更新类型 (patch/minor/major)
            update_type=$(echo "$body" | grep -oP '\|\s*(patch|minor|major)\s*\|' | head -n1 | tr -d '|[:space:]')

            echo "PR #$pr update type: $update_type"

            if [[ "$update_type" == "patch" || "$update_type" == "minor" ]]; then
              echo "Merging PR #$pr ..."
              gh pr merge "$pr" \
                --repo ${{ github.repository }} \
                --squash \
                --auto
            else
              echo "Skipping PR #$pr (type=$update_type)"
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
