name: Renovate

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
    inputs:
      manual-trigger:
        description: 'Manually trigger Renovate'
        default: ''

jobs:
  renovate:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.19
        with:
          useSlim: false
          token: ${{ secrets.GITHUBTOKEN }}
